openapi: 3.0.1
info:
  title: Componenti riusabili per INAD
  description: |-
    API rese disponibili da INAD al Catalogo delle API previsto nel modello di interoperabilità delle pubbliche amministrazioni accessibile da ANPR.
  contact:
    name: AgID - Agenzia per l'Italia Digitale
    url: https://www.agid.gov.it/
  license:
    name: CC BY-NC-SA 4.0
    url: https://creativecommons.org/licenses/by-nc-sa/4.0/
  version: 1.0.0
servers: []
paths: {}
tags: []
components:
  headers:
    Agid-JWS-Signature:
      description: |-
        L'header Agid-JWS-Signature è un JWS (JSON Web Signature) che contiene una firma digitale
        associata al messaggio scambiato.
      schema:
        type: string
        format: JWS
        maxLength: 4096
        example: eyJzd.fafa.fafafa
  responses:
    '400':
      description: BAD_REQUEST
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Errore'
    '401':
      description: UNAUTHORIZED
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Errore'
    '403':
      description: FORBIDDEN
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Errore'
    '404':
      description: NOT_FOUND
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Errore'
    '500':
      description: INTERNAL_SERVER_ERROR
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Errore'
    '503':
      description: SERVICE_UNAVAILABLE
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Errore'

  schemas:
    RequestCode:
      description: |-
        Il codice identificativo di una richiesta di variazione
        di domicilio digitale.

        La richiesta contiene l'identificativo della piattaforma
        utilizzata per la richiesta (INAD, ANPR, APPIO).

        TODO: rinominare perché i termini Request e Code sono
        ambigui in un'API :)
      type: string
      pattern: ^(INAD|ANPR|APPIO)_[0-9]{10,10}

    ACK:
      type: string
      description: TODO Cosa significa?
      enum:
        - chargeMade

    Email:
      type: string
      pattern: ^([a-zA-Z0-9_\-\.]+)@([a-zA-Z0-9_\-\.]+)\.([a-zA-Z]{2,5})$
    CodiceFiscale:
      description: |-
        Il codice fiscale di una persona fisica.
      type: string
      pattern: /^(?:[A-Z][AEIOU][AEIOUX]|[B-DF-HJ-NP-TV-Z]{2}[A-Z]){2}(?:[\dLMNP-V]{2}(?:[A-EHLMPR-T](?:[04LQ][1-9MNP-V]|[15MR][\dLMNP-V]|[26NS][0-8LMNP-U])|[DHPS][37PT][0L]|[ACELMRT][37PT][01LM]|[AC-EHLMPR-T][26NS][9V])|(?:[02468LNQSU][048LQU]|[13579MPRTV][26NS])B[26NS][9V])(?:[A-MZ][1-9MNP-V][\dLMNP-V]{2}|[A-M][0L](?:[1-9MNP-V][\dLMNP-V]|[0L][1-9MNP-V]))[A-Z]$/i
    CitizenStatus:
      description: |-
        In INAD un cittadino può trovarsi in uno dei seguenti stati.
      type: string
      enum:
        - citizenNotPresent             #  non registrato
        - digitalDomicileNotPresent     # registrato ma il domicilio digitale non è stato eletto
        - inCharge                      # registrato e risulta l'avvio di una richiesta
        - verify                        # registrato con una richiesta in verifica
        - confirmationRequestSent       # registrato ed è stata mandata conferma della richiesta alla PEC o email di contatto
        - awaitingPublication           # registrato con una richiesta in attesa di pubblicazione
        - waitingOfficeCancellation     # FIXME
        - digitalDomicilePresent        # registrato e il domicilio digitale è stato eletto



    Errore:
      required:
        - status
        - title
      type: object
      additionalProperties: false
      description: Modello di risposta in caso di errore
      properties:
        status:
          type: integer
          format: int32
          description: Codice di errore
          example: 400
          maximum: 600
          minimum: 100
        title:
          type: string
          description: Tipologia di errore
          example: BAD_REQUEST
          enum:
            - BAD_REQUEST
            - UNAUTHORIZED
            - FORBIDDEN
            - NOT_FOUND
            - INTERNAL_SERVER_ERROR
            - SERVICE_UNAVAILABLE
        detail:
          type: string
          description: Descrizione di dettaglio dello specifico problema verificatosi
          example: <detail_error>
          maxLength: 1024
